parameters:
    i_xarlie_mutex.locker_flock.cache_dir: ~
    i_xarlie_mutex.locker_redis.client: ~
    i_xarlie_mutex.locker_memcache.client: ~
    i_xarlie_mutex.locker_memcached.client: ~

services:

    ninja_mutex.locker_flock:
        class: NinjaMutex\Lock\FlockLock
        public: false
        arguments:
            - %i_xarlie_mutex.locker_flock.cache_dir%

    ninja_mutex.locker_redis:
        class: NinjaMutex\Lock\PredisRedisLock
        public: false
        arguments:
            - '%i_xarlie_mutex.locker_redis.client%'

    ninja_mutex.locker_memcache:
        class: NinjaMutex\Lock\MemcacheLock
        public: false
        arguments:
            - '%i_xarlie_mutex.locker_memcache.client%'

    ninja_mutex.locker_memcached:
        class: NinjaMutex\Lock\MemcachedLock
        public: false
        arguments:
            - '%i_xarlie_mutex.locker_memcached.client%'

#    ninja_mutex.locker_mysql:
#        class: NinjaMutex\Lock\MySqlLock
#        public: false
#        arguments:
#            - '%i_xarlie_mutex.locker_mysql.username%'
#            - '%i_xarlie_mutex.locker_mysql.password%'
#            - '%i_xarlie_mutex.locker_mysql.host%'
#            - '%i_xarlie_mutex.locker_mysql.port%'
#            - '%i_xarlie_mutex.locker_mysql.class_name%'
