parameters:
  i_xarlie_mutex.controller.listener.class: IXarlie\MutexBundle\EventListener\MutexRequestListener

services:
  i_xarlie_mutex.controller.listener:
    class: '%i_xarlie_mutex.controller.listener.class%'
    arguments:
      - '@annotation_reader'
    tags:
      - { name: kernel.event_subscriber }
